### ISSUE TITLE
Problem getting badges to work using badges_list

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#16]
I've been trying to get badges working using option 2 as outlined in the documentation with no luck. Option 1 works:
```
  customize_glob:
    "*.*":
      custom_ui_state_card: custom-ui
    group.inner_group:
      state_card_mode: badges

group:
  inner_group:
    entities:
      - sensor.office_energy_period
      - sensor.office_energy_current
      - sensor.office_energy_power
      - sensor.office_energy_voltage
      - sensor.office_energy_factor
  outer_group:
    entities:
      - group.inner_group
      - sensor.office_energy_yesterday
      - sensor.office_energy_yesterday_cost
      - sensor.office_energy_today
      - sensor.office_energy_today_cost
```
Resulting in:
![image](https://user-images.githubusercontent.com/3755059/27767372-99ac35c6-5f39-11e7-9864-4eeb6ade3697.png)
But option 2 (if I am using it correctly) does not:
```
  customize_glob:
    "*.*":
      custom_ui_state_card: custom-ui
    group.inner_group:
      state_card_mode: badges
      badges_list:
        - sensor.office_energy_period
        - sensor.office_energy_current
        - sensor.office_energy_power
        - sensor.office_energy_voltage
        - sensor.office_energy_factor

group:
  inner_group:
    entities:
      - sensor.office_energy_period
      - sensor.office_energy_current
      - sensor.office_energy_power
      - sensor.office_energy_voltage
      - sensor.office_energy_factor
      - sensor.office_energy_yesterday
      - sensor.office_energy_yesterday_cost
      - sensor.office_energy_today
      - sensor.office_energy_today_cost
```
Results in:
![image](https://user-images.githubusercontent.com/3755059/27767414-88157150-5f3a-11e7-9764-d9dfddf11692.png)
I have a lot of existing groups that I would like to modify with badges so I was hoping that I could get the second option working.

Is there anything in my config that is incorrect?

P.S. I have no idea why the group in option 1 took on the context naming of group.office_energy. They both should have shown the full names for the entities.

**Comment by andrey-git** [comment]
Option2 still has "inner group" and "outer group". The difference Option2 this and Option1 is that by using `badges_list` you show only *part* of "inner group" as badges in "outer group". I have updated the docs to be more clear on this point.

If you have existing groups and you want to show *part* of such group as badges - user Option3

**Comment by mihalski** [comment]
It seems no matter which option I choose I can't leave the existing groups in place but must modify them (at least sligthly). Am I understanding that correctly?
The updated documentation has helped a lot, but I am still struggling to get it working. I've got the following configuration:
```
  customize_glob:
    "*.*":
      custom_ui_state_card: custom-ui
    group.office_energy:
      state_card_mode: badges
      badges_list:
        - sensor.office_energy_period
        - sensor.office_energy_current
        - sensor.office_energy_power
        - sensor.office_energy_voltage
        - sensor.office_energy_factor
    sensor.office_energy_period:
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_current:
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_power:
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_voltage:
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_factor:
      group:
        group.office_energy:
          hidden: true

group:
  office_energy:
    entities:
      - sensor.office_energy_period
      - sensor.office_energy_current
      - sensor.office_energy_power
      - sensor.office_energy_voltage
      - sensor.office_energy_factor
      - group.office_energy
      - sensor.office_energy_yesterday
      - sensor.office_energy_yesterday_cost
      - sensor.office_energy_today
      - sensor.office_energy_today_cost
```
But it still results in something other than expected:
![image](https://user-images.githubusercontent.com/3755059/27767903-168676d8-5f49-11e7-9446-fb81c0a4ae4c.png)
Am I just blind to some detail of the configuration being incorrect or misunderstanding the documentation?

Regards,
Michal

**Comment by andrey-git** [comment]
The configuration seems correct.
Does 
```
group:
  <group_name>:
    hidden: true
```
work for you in any other setting?


Yes, a slight group modification is needed so a group will include itself. (But you don't need to add new groups with Option3)

**Comment by mihalski** [comment]
Yes it does seem to work. I randomly chose a group.
```
homeassistant:
  customize:
    group.family_room:
      hidden: true
      friendly_name: "Family Room"
```
This hides the previously visible group.family_room

**Comment by andrey-git** [comment]
This is different, this is the core `hidden` functionality.

I was wondering if context-aware hide works for you without using badges
i.e.
```
homeassistant:
  customize:
    <entity in family group here>:
      group:
        group.family_room:
          hidden: true
```

**Comment by mihalski** [comment]
Ahh.. I'll try it now.. The context aware naming (mostly) works (except for the weird issue I logged earlier).

**Comment by mihalski** [comment]
It's not working.. I've pared my config down to almost nothing.. Just this and zwave (which is where the sensors for group,family_room come from).
```
home:assistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: custom-ui
  customize:
    sensor.family_room_temperature:
      group:
        group.family_room:
          hidden: true

group:
  family_room:
    entities:
      - binary_sensor.family_room_sensor
      - sensor.family_room_temperature
      - sensor.family_room_relative_humidity
      - sensor.family_room_luminance
```
But it still shows the temperature.

**Comment by andrey-git** [comment]
Just to make sure: You have have the last (today's) version of CustomUI, right?

**Comment by andrey-git** [comment]
Also, after editing the config you need to restart HA or "reload core config" + change entity state + reload UI

(I always restart HA so I'm sure the changes picked up)

**Comment by mihalski** [comment]
I believe so, but the show_last_changed being set to true still only affected lights when I had everything configured, so I have some doubt. Is there a way to get the version of the custom-ui from the entity editor?

I also always restart, except in my case I'm using HASSIO so I'm literally restarting the entire container every time.

I really don'y know why it's not working for me. There must be some explanation.

**Comment by andrey-git** [comment]
I pushed a new version that will print the version to browser dev console.

Here are file sizes for reference:
-rw-rw-r-- 1 ... 12686 Jul  2 12:30 state-card-custom-ui.html
-rw-rw-r-- 1 ...   3979 Jul  2 12:30 state-card-custom-ui.html.gz

**Comment by mihalski** [comment]
So I had an older version from a bit earlier in the day I guess:
```
-rw-r--r--    1 root     root         12646 Jul  2 00:14 state-card-custom-ui.html
-rw-r--r--    1 root     root          3952 Jul  2 00:14 state-card-custom-ui.html.gz
```
Now I have:
```
-rw-r--r--    1 root     root         12686 Jul  2 02:31 state-card-custom-ui.html
-rw-r--r--    1 root     root          3979 Jul  2 02:31 state-card-custom-ui.html.gz
```
Now show_last_changed is working (and it's AMAZING to finally have this), but hiding an entity contextually still isn't. I've shift-reloaded in case that was the problem. It's bizarre.

**Comment by mihalski** [comment]
I GOT IT!

I kept tweaking and rearranging until finally it worked.. Now I just have to figure out what it is that I finally did differently.

**Comment by mihalski** [comment]
LOL! It just WON'T let me have it :P

I got the hiding to work so the contextual naming stopped working. Still works for Family Room though.
![image](https://user-images.githubusercontent.com/3755059/27769113-3296b438-5f66-11e7-8ab9-6c67af5a995a.png)
Here's the relevant config:
```
homeassistant:
  customize:
    group.office_energy:
      friendly_name: "Office Energy"
      state_card_mode: badges
      badges_list:
        - sensor.office_energy_period
        - sensor.office_energy_current
        - sensor.office_energy_power
        - sensor.office_energy_voltage
        - sensor.office_energy_factor

    sensor.office_energy_period:
      friendly_name: Office Energy Period
      friendly_names:
        group.office_energy: Period
        group.office_energy_view: Period
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_current:
      friendly_name: Office Energy Current
      friendly_names:
        group.office_energy: Current
        group.office_energy_view: Current
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_power:
      friendly_name: Office Energy Power
      friendly_names:
        group.office_energy: Power
        group.office_energy_view: Power
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_voltage:
      friendly_name: Office Energy Voltage
      friendly_names:
        group.office_energy: Voltage
        group.office_energy_view: Voltage
      group:
        group.office_energy:
          hidden: true
    sensor.office_energy_factor:
      friendly_name: Office Energy Factor
      friendly_names:
        group.office_energy: Factor
        group.office_energy_view: Factor
      group:
        group.office_energy:
          hidden: true

group:
  office_energy:
    entities:
      - sensor.office_energy_period
      - sensor.office_energy_current
      - sensor.office_energy_power
      - sensor.office_energy_voltage
      - sensor.office_energy_factor
      - group.office_energy
      - sensor.office_energy_yesterday
      - sensor.office_energy_yesterday_cost
      - sensor.office_energy_today
      - sensor.office_energy_today_cost
```
Do any problems stand out?

**Comment by mihalski** [comment]
Well the context naming also stopped working for group.family_room at some stage as I rebuilt my config (by moving files alone since I use packages), and now I've moved all the way back to before even adding energy sensors and still context naming is not working..
Order if the tags in the customize section shouldn't matter should it?

**Comment by andrey-git** [comment]
Order of the tags doesn't matter unless you have conflicting globs. In that case it will resolve in-order:
```
sensor.*
  value: A
sensor*:
  value: B
```
The "value" will be "B" for all sensors.

**Comment by mihalski** [comment]
So if there are conflicts the last item takes precedence and overrides any earlier value set?

Still even if I had something like that I don't see how I could override the friendly_names. I know it can work because it worked just fine even a few hours ago :/

I mean.. It says it right there!
![image](https://user-images.githubusercontent.com/3755059/27769316-8cab3f58-5f6a-11e7-90d3-fbf89678186e.png)

**Comment by andrey-git** [comment]
Oh, the 2017-07-01 CustomUI release changed the syntax of that:
now it is a common
```
group:
  <group_name>:
    <attribute>: <value>
```
syntax.

For example:

```
sensor.office_energy_factor:
      friendly_name: Office Energy Factor
      group:
        group.office_energy:
          hidden: true
          friendly_name: Factor
        group.office_energy_view:
          friendly_name: Factor
```

**Comment by mihalski** [comment]
I MUCH prefer the new syntax.
Needed to teach myself regular expressions and construct some to automate the changes. It worked!
It will be somewhat more challenging to craft a regular expression that can bulk update the 400 lines of energy monitor customization.. I have faith.

**Comment by mihalski** [comment]
OK. All working.. Still seems to be a bug when resizing the window (or hiding the side panel) where the customization just turns off depending on the amount of available space.

Am I crazy or is there no way to have context aware group names (ie Office Energy vs  Office when in the Energy view/group) without completely duplicating the group and associated custom-ui? In particular with groups that contain some badges.

I think I'm finally beginning to get a tenuous grasp on this, but my customization section just for the energy package has grown to almost 700 lines :P
