### ISSUE TITLE
Custom UI broken with 0.84.1: custom_ui/state-card-custom-ui.html:27:15926 Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ReX1983** [andrey-git/home-assistant-custom-ui#161]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 71.0.3578.75

**CustomUI version:** 20180831

**Home Assistant release (`hass --version`):** 0.84.1 

**Problem-relevant `configuration.yaml` entries:**
```yaml

```

**Problem-relevant Home Assistant log entries:**
```
[...]local/custom_ui/state-card-custom-ui.html:27:15926 Uncaught TypeError: Class extends value undefined is not a constructor or null
10:36 PM components/system_log/__init__.py (ERROR)
```

**Any errors from browser Javascript console:**
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (dynamic-with-extra.js:10)
    at i (bootstrap:19)
    at bootstrap:68
    at bootstrap:68
(anonymous) @ dynamic-with-extra.js:10
i @ bootstrap:19
(anonymous) @ bootstrap:68
(anonymous) @ bootstrap:68
```

I've just updated to 0.84.1 and all the groups are empty/blank.

Hope the logs above help!

**Comment by bratanon** [comment]
Same here when using customize_glob

```
"*.*":
  custom_ui_state_card: state-card-custom-ui
  show_last_changed: true
```

**Comment by atom83** [comment]
similar issue with my hass:

  ```
 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (state-card-custom-ui.html:27)
    at i (state-card-custom-ui.html:2)
    at state-card-custom-ui.html:2
    at state-card-custom-ui.html:2
```

**Comment by artomka** [comment]
I have the same issue on 0.84.1 Hass.io.

**Comment by Mariusthvdb** [comment]
+1
no more regular weather component cards in regular HA, customizations fail to show (icons, last_changed etc etc)
also more-info popup for Tiles don't show. No more state-card mode badges.

All suddenly stopped working after 0.84.1 and still in perfect order while on 0.83.x

Hope a fix is made soon, since Lovelace itself is still a bit of an experiment, and not to be relied on for an automated home just yet...

**Comment by andrey-git** [comment]
Fixed by release 2018-12-17

**Comment by crus1313** [comment]
Also custom badges don't change color anymore. I cannot update CustomUI: beyond 20180831. I did manual install (github) and via update.sh (no errors), none updated beyond CustomUI: 20180831.

**Comment by kt666** [comment]
Same issues as crus1313 here.. tried the update more times.. still the same.
