### ISSUE TITLE
extra badge unit not available and showing 'none' below badge

### ISSUE THREAD

**Issue by Mariusthvdb** [andrey-git/home-assistant-custom-ui#167]
### Checklist
- [ ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [ ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [ ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 

**CustomUI version:** 
20190113 but was also on 20181217
**Home Assistant release (`hass --version`):** 
0.84.6, not happening on 0.84.3

**Problem-relevant `configuration.yaml` entries:**
```yaml
light.lounge_chair_long:
  icon: mdi:seat-recline-extra
  extra_data_template: >
    if (attributes.hs_color) 
        return 'Hs: ' + attributes.hs_color;
    return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: true
  confirm_controls: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: true
    report_when_not_changed: true
  extra_badge:
    - attribute: brightness
      unit: Br

```

**Problem-relevant Home Assistant log entries:**
```
```
![schermafbeelding 2019-01-24 om 11 11 43](https://user-images.githubusercontent.com/33354141/51671306-ea84c200-1fc8-11e9-9eb6-d44f3a7a91e8.jpg)

**Any errors from browser Javascript console:**
```

```

don't see any

![schermafbeelding 2019-01-24 om 11 05 02](https://user-images.githubusercontent.com/33354141/51671467-4d765900-1fc9-11e9-91b7-fd4364b01f8f.jpg)

this is what it is supposed to look like:

![schermafbeelding 2019-01-24 om 11 05 26](https://user-images.githubusercontent.com/33354141/51671343-00928280-1fc9-11e9-8b87-12044c333f48.jpg)

**Comment by andrey-git** [comment]
This should have been fixed by `2019-01-13`

**Comment by Mariusthvdb** [comment]
HI @andrey-git ,

this is still not as it used to be: units under the badges are not displayed any more, please see https://github.com/andrey-git/home-assistant-custom-ui/issues/165#issuecomment-479467788
